// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface ChatIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.ChatId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 chatId = 1;</code>
   * @return The chatId.
   */
  long getChatId();
}
