// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

/**
 * Protobuf type {@code dk.via.mithus.protobuf.Cost}
 */
public final class Cost extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dk.via.mithus.protobuf.Cost)
    CostOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Cost.newBuilder() to construct.
  private Cost(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Cost() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Cost();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Cost(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 17: {

            deposit_ = input.readDouble();
            break;
          }
          case 25: {

            moveInPrice_ = input.readDouble();
            break;
          }
          case 33: {

            utilities_ = input.readDouble();
            break;
          }
          case 41: {

            monthlyRent_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Cost_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Cost_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.mithus.protobuf.Cost.class, dk.via.mithus.protobuf.Cost.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int DEPOSIT_FIELD_NUMBER = 2;
  private double deposit_;
  /**
   * <code>double deposit = 2;</code>
   * @return The deposit.
   */
  @java.lang.Override
  public double getDeposit() {
    return deposit_;
  }

  public static final int MOVEINPRICE_FIELD_NUMBER = 3;
  private double moveInPrice_;
  /**
   * <code>double moveInPrice = 3;</code>
   * @return The moveInPrice.
   */
  @java.lang.Override
  public double getMoveInPrice() {
    return moveInPrice_;
  }

  public static final int UTILITIES_FIELD_NUMBER = 4;
  private double utilities_;
  /**
   * <code>double utilities = 4;</code>
   * @return The utilities.
   */
  @java.lang.Override
  public double getUtilities() {
    return utilities_;
  }

  public static final int MONTHLYRENT_FIELD_NUMBER = 5;
  private double monthlyRent_;
  /**
   * <code>double monthlyRent = 5;</code>
   * @return The monthlyRent.
   */
  @java.lang.Override
  public double getMonthlyRent() {
    return monthlyRent_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (java.lang.Double.doubleToRawLongBits(deposit_) != 0) {
      output.writeDouble(2, deposit_);
    }
    if (java.lang.Double.doubleToRawLongBits(moveInPrice_) != 0) {
      output.writeDouble(3, moveInPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(utilities_) != 0) {
      output.writeDouble(4, utilities_);
    }
    if (java.lang.Double.doubleToRawLongBits(monthlyRent_) != 0) {
      output.writeDouble(5, monthlyRent_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (java.lang.Double.doubleToRawLongBits(deposit_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, deposit_);
    }
    if (java.lang.Double.doubleToRawLongBits(moveInPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, moveInPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(utilities_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, utilities_);
    }
    if (java.lang.Double.doubleToRawLongBits(monthlyRent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, monthlyRent_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.mithus.protobuf.Cost)) {
      return super.equals(obj);
    }
    dk.via.mithus.protobuf.Cost other = (dk.via.mithus.protobuf.Cost) obj;

    if (getId()
        != other.getId()) return false;
    if (java.lang.Double.doubleToLongBits(getDeposit())
        != java.lang.Double.doubleToLongBits(
            other.getDeposit())) return false;
    if (java.lang.Double.doubleToLongBits(getMoveInPrice())
        != java.lang.Double.doubleToLongBits(
            other.getMoveInPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getUtilities())
        != java.lang.Double.doubleToLongBits(
            other.getUtilities())) return false;
    if (java.lang.Double.doubleToLongBits(getMonthlyRent())
        != java.lang.Double.doubleToLongBits(
            other.getMonthlyRent())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + DEPOSIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDeposit()));
    hash = (37 * hash) + MOVEINPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMoveInPrice()));
    hash = (37 * hash) + UTILITIES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUtilities()));
    hash = (37 * hash) + MONTHLYRENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMonthlyRent()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.mithus.protobuf.Cost parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Cost parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.Cost parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.Cost parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.mithus.protobuf.Cost prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dk.via.mithus.protobuf.Cost}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dk.via.mithus.protobuf.Cost)
      dk.via.mithus.protobuf.CostOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Cost_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Cost_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.mithus.protobuf.Cost.class, dk.via.mithus.protobuf.Cost.Builder.class);
    }

    // Construct using dk.via.mithus.protobuf.Cost.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      deposit_ = 0D;

      moveInPrice_ = 0D;

      utilities_ = 0D;

      monthlyRent_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Cost_descriptor;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.Cost getDefaultInstanceForType() {
      return dk.via.mithus.protobuf.Cost.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.Cost build() {
      dk.via.mithus.protobuf.Cost result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.Cost buildPartial() {
      dk.via.mithus.protobuf.Cost result = new dk.via.mithus.protobuf.Cost(this);
      result.id_ = id_;
      result.deposit_ = deposit_;
      result.moveInPrice_ = moveInPrice_;
      result.utilities_ = utilities_;
      result.monthlyRent_ = monthlyRent_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.mithus.protobuf.Cost) {
        return mergeFrom((dk.via.mithus.protobuf.Cost)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.mithus.protobuf.Cost other) {
      if (other == dk.via.mithus.protobuf.Cost.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getDeposit() != 0D) {
        setDeposit(other.getDeposit());
      }
      if (other.getMoveInPrice() != 0D) {
        setMoveInPrice(other.getMoveInPrice());
      }
      if (other.getUtilities() != 0D) {
        setUtilities(other.getUtilities());
      }
      if (other.getMonthlyRent() != 0D) {
        setMonthlyRent(other.getMonthlyRent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.mithus.protobuf.Cost parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.mithus.protobuf.Cost) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private double deposit_ ;
    /**
     * <code>double deposit = 2;</code>
     * @return The deposit.
     */
    @java.lang.Override
    public double getDeposit() {
      return deposit_;
    }
    /**
     * <code>double deposit = 2;</code>
     * @param value The deposit to set.
     * @return This builder for chaining.
     */
    public Builder setDeposit(double value) {
      
      deposit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double deposit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeposit() {
      
      deposit_ = 0D;
      onChanged();
      return this;
    }

    private double moveInPrice_ ;
    /**
     * <code>double moveInPrice = 3;</code>
     * @return The moveInPrice.
     */
    @java.lang.Override
    public double getMoveInPrice() {
      return moveInPrice_;
    }
    /**
     * <code>double moveInPrice = 3;</code>
     * @param value The moveInPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMoveInPrice(double value) {
      
      moveInPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double moveInPrice = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoveInPrice() {
      
      moveInPrice_ = 0D;
      onChanged();
      return this;
    }

    private double utilities_ ;
    /**
     * <code>double utilities = 4;</code>
     * @return The utilities.
     */
    @java.lang.Override
    public double getUtilities() {
      return utilities_;
    }
    /**
     * <code>double utilities = 4;</code>
     * @param value The utilities to set.
     * @return This builder for chaining.
     */
    public Builder setUtilities(double value) {
      
      utilities_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double utilities = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtilities() {
      
      utilities_ = 0D;
      onChanged();
      return this;
    }

    private double monthlyRent_ ;
    /**
     * <code>double monthlyRent = 5;</code>
     * @return The monthlyRent.
     */
    @java.lang.Override
    public double getMonthlyRent() {
      return monthlyRent_;
    }
    /**
     * <code>double monthlyRent = 5;</code>
     * @param value The monthlyRent to set.
     * @return This builder for chaining.
     */
    public Builder setMonthlyRent(double value) {
      
      monthlyRent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double monthlyRent = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMonthlyRent() {
      
      monthlyRent_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dk.via.mithus.protobuf.Cost)
  }

  // @@protoc_insertion_point(class_scope:dk.via.mithus.protobuf.Cost)
  private static final dk.via.mithus.protobuf.Cost DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.mithus.protobuf.Cost();
  }

  public static dk.via.mithus.protobuf.Cost getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Cost>
      PARSER = new com.google.protobuf.AbstractParser<Cost>() {
    @java.lang.Override
    public Cost parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Cost(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Cost> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Cost> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.mithus.protobuf.Cost getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

