// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

/**
 * Protobuf type {@code dk.via.mithus.protobuf.EnergyRatings}
 */
public final class EnergyRatings extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dk.via.mithus.protobuf.EnergyRatings)
    EnergyRatingsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnergyRatings.newBuilder() to construct.
  private EnergyRatings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnergyRatings() {
    energyRatings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnergyRatings();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnergyRatings(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              energyRatings_ = new java.util.ArrayList<dk.via.mithus.protobuf.EnergyRating>();
              mutable_bitField0_ |= 0x00000001;
            }
            energyRatings_.add(
                input.readMessage(dk.via.mithus.protobuf.EnergyRating.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        energyRatings_ = java.util.Collections.unmodifiableList(energyRatings_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_EnergyRatings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_EnergyRatings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.mithus.protobuf.EnergyRatings.class, dk.via.mithus.protobuf.EnergyRatings.Builder.class);
  }

  public static final int ENERGYRATINGS_FIELD_NUMBER = 1;
  private java.util.List<dk.via.mithus.protobuf.EnergyRating> energyRatings_;
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<dk.via.mithus.protobuf.EnergyRating> getEnergyRatingsList() {
    return energyRatings_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dk.via.mithus.protobuf.EnergyRatingOrBuilder> 
      getEnergyRatingsOrBuilderList() {
    return energyRatings_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  @java.lang.Override
  public int getEnergyRatingsCount() {
    return energyRatings_.size();
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.EnergyRating getEnergyRatings(int index) {
    return energyRatings_.get(index);
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.EnergyRatingOrBuilder getEnergyRatingsOrBuilder(
      int index) {
    return energyRatings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < energyRatings_.size(); i++) {
      output.writeMessage(1, energyRatings_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < energyRatings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, energyRatings_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.mithus.protobuf.EnergyRatings)) {
      return super.equals(obj);
    }
    dk.via.mithus.protobuf.EnergyRatings other = (dk.via.mithus.protobuf.EnergyRatings) obj;

    if (!getEnergyRatingsList()
        .equals(other.getEnergyRatingsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEnergyRatingsCount() > 0) {
      hash = (37 * hash) + ENERGYRATINGS_FIELD_NUMBER;
      hash = (53 * hash) + getEnergyRatingsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.EnergyRatings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.mithus.protobuf.EnergyRatings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dk.via.mithus.protobuf.EnergyRatings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dk.via.mithus.protobuf.EnergyRatings)
      dk.via.mithus.protobuf.EnergyRatingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_EnergyRatings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_EnergyRatings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.mithus.protobuf.EnergyRatings.class, dk.via.mithus.protobuf.EnergyRatings.Builder.class);
    }

    // Construct using dk.via.mithus.protobuf.EnergyRatings.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEnergyRatingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (energyRatingsBuilder_ == null) {
        energyRatings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        energyRatingsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_EnergyRatings_descriptor;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.EnergyRatings getDefaultInstanceForType() {
      return dk.via.mithus.protobuf.EnergyRatings.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.EnergyRatings build() {
      dk.via.mithus.protobuf.EnergyRatings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.EnergyRatings buildPartial() {
      dk.via.mithus.protobuf.EnergyRatings result = new dk.via.mithus.protobuf.EnergyRatings(this);
      int from_bitField0_ = bitField0_;
      if (energyRatingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          energyRatings_ = java.util.Collections.unmodifiableList(energyRatings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.energyRatings_ = energyRatings_;
      } else {
        result.energyRatings_ = energyRatingsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.mithus.protobuf.EnergyRatings) {
        return mergeFrom((dk.via.mithus.protobuf.EnergyRatings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.mithus.protobuf.EnergyRatings other) {
      if (other == dk.via.mithus.protobuf.EnergyRatings.getDefaultInstance()) return this;
      if (energyRatingsBuilder_ == null) {
        if (!other.energyRatings_.isEmpty()) {
          if (energyRatings_.isEmpty()) {
            energyRatings_ = other.energyRatings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEnergyRatingsIsMutable();
            energyRatings_.addAll(other.energyRatings_);
          }
          onChanged();
        }
      } else {
        if (!other.energyRatings_.isEmpty()) {
          if (energyRatingsBuilder_.isEmpty()) {
            energyRatingsBuilder_.dispose();
            energyRatingsBuilder_ = null;
            energyRatings_ = other.energyRatings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            energyRatingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEnergyRatingsFieldBuilder() : null;
          } else {
            energyRatingsBuilder_.addAllMessages(other.energyRatings_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.mithus.protobuf.EnergyRatings parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.mithus.protobuf.EnergyRatings) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<dk.via.mithus.protobuf.EnergyRating> energyRatings_ =
      java.util.Collections.emptyList();
    private void ensureEnergyRatingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        energyRatings_ = new java.util.ArrayList<dk.via.mithus.protobuf.EnergyRating>(energyRatings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.EnergyRating, dk.via.mithus.protobuf.EnergyRating.Builder, dk.via.mithus.protobuf.EnergyRatingOrBuilder> energyRatingsBuilder_;

    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.EnergyRating> getEnergyRatingsList() {
      if (energyRatingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(energyRatings_);
      } else {
        return energyRatingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public int getEnergyRatingsCount() {
      if (energyRatingsBuilder_ == null) {
        return energyRatings_.size();
      } else {
        return energyRatingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public dk.via.mithus.protobuf.EnergyRating getEnergyRatings(int index) {
      if (energyRatingsBuilder_ == null) {
        return energyRatings_.get(index);
      } else {
        return energyRatingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder setEnergyRatings(
        int index, dk.via.mithus.protobuf.EnergyRating value) {
      if (energyRatingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnergyRatingsIsMutable();
        energyRatings_.set(index, value);
        onChanged();
      } else {
        energyRatingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder setEnergyRatings(
        int index, dk.via.mithus.protobuf.EnergyRating.Builder builderForValue) {
      if (energyRatingsBuilder_ == null) {
        ensureEnergyRatingsIsMutable();
        energyRatings_.set(index, builderForValue.build());
        onChanged();
      } else {
        energyRatingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder addEnergyRatings(dk.via.mithus.protobuf.EnergyRating value) {
      if (energyRatingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnergyRatingsIsMutable();
        energyRatings_.add(value);
        onChanged();
      } else {
        energyRatingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder addEnergyRatings(
        int index, dk.via.mithus.protobuf.EnergyRating value) {
      if (energyRatingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnergyRatingsIsMutable();
        energyRatings_.add(index, value);
        onChanged();
      } else {
        energyRatingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder addEnergyRatings(
        dk.via.mithus.protobuf.EnergyRating.Builder builderForValue) {
      if (energyRatingsBuilder_ == null) {
        ensureEnergyRatingsIsMutable();
        energyRatings_.add(builderForValue.build());
        onChanged();
      } else {
        energyRatingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder addEnergyRatings(
        int index, dk.via.mithus.protobuf.EnergyRating.Builder builderForValue) {
      if (energyRatingsBuilder_ == null) {
        ensureEnergyRatingsIsMutable();
        energyRatings_.add(index, builderForValue.build());
        onChanged();
      } else {
        energyRatingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder addAllEnergyRatings(
        java.lang.Iterable<? extends dk.via.mithus.protobuf.EnergyRating> values) {
      if (energyRatingsBuilder_ == null) {
        ensureEnergyRatingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, energyRatings_);
        onChanged();
      } else {
        energyRatingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder clearEnergyRatings() {
      if (energyRatingsBuilder_ == null) {
        energyRatings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        energyRatingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public Builder removeEnergyRatings(int index) {
      if (energyRatingsBuilder_ == null) {
        ensureEnergyRatingsIsMutable();
        energyRatings_.remove(index);
        onChanged();
      } else {
        energyRatingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public dk.via.mithus.protobuf.EnergyRating.Builder getEnergyRatingsBuilder(
        int index) {
      return getEnergyRatingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public dk.via.mithus.protobuf.EnergyRatingOrBuilder getEnergyRatingsOrBuilder(
        int index) {
      if (energyRatingsBuilder_ == null) {
        return energyRatings_.get(index);  } else {
        return energyRatingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public java.util.List<? extends dk.via.mithus.protobuf.EnergyRatingOrBuilder> 
         getEnergyRatingsOrBuilderList() {
      if (energyRatingsBuilder_ != null) {
        return energyRatingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(energyRatings_);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public dk.via.mithus.protobuf.EnergyRating.Builder addEnergyRatingsBuilder() {
      return getEnergyRatingsFieldBuilder().addBuilder(
          dk.via.mithus.protobuf.EnergyRating.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public dk.via.mithus.protobuf.EnergyRating.Builder addEnergyRatingsBuilder(
        int index) {
      return getEnergyRatingsFieldBuilder().addBuilder(
          index, dk.via.mithus.protobuf.EnergyRating.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.EnergyRating.Builder> 
         getEnergyRatingsBuilderList() {
      return getEnergyRatingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.EnergyRating, dk.via.mithus.protobuf.EnergyRating.Builder, dk.via.mithus.protobuf.EnergyRatingOrBuilder> 
        getEnergyRatingsFieldBuilder() {
      if (energyRatingsBuilder_ == null) {
        energyRatingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.via.mithus.protobuf.EnergyRating, dk.via.mithus.protobuf.EnergyRating.Builder, dk.via.mithus.protobuf.EnergyRatingOrBuilder>(
                energyRatings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        energyRatings_ = null;
      }
      return energyRatingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dk.via.mithus.protobuf.EnergyRatings)
  }

  // @@protoc_insertion_point(class_scope:dk.via.mithus.protobuf.EnergyRatings)
  private static final dk.via.mithus.protobuf.EnergyRatings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.mithus.protobuf.EnergyRatings();
  }

  public static dk.via.mithus.protobuf.EnergyRatings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnergyRatings>
      PARSER = new com.google.protobuf.AbstractParser<EnergyRatings>() {
    @java.lang.Override
    public EnergyRatings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnergyRatings(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnergyRatings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnergyRatings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.mithus.protobuf.EnergyRatings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

