// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface EnergyRatingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.EnergyRatings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  java.util.List<dk.via.mithus.protobuf.EnergyRating> 
      getEnergyRatingsList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  dk.via.mithus.protobuf.EnergyRating getEnergyRatings(int index);
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  int getEnergyRatingsCount();
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  java.util.List<? extends dk.via.mithus.protobuf.EnergyRatingOrBuilder> 
      getEnergyRatingsOrBuilderList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.EnergyRating energyRatings = 1;</code>
   */
  dk.via.mithus.protobuf.EnergyRatingOrBuilder getEnergyRatingsOrBuilder(
      int index);
}
