// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface HousingTypesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.HousingTypes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dk.via.mithus.protobuf.HousingType housingTypes = 1;</code>
   */
  java.util.List<dk.via.mithus.protobuf.HousingType> 
      getHousingTypesList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.HousingType housingTypes = 1;</code>
   */
  dk.via.mithus.protobuf.HousingType getHousingTypes(int index);
  /**
   * <code>repeated .dk.via.mithus.protobuf.HousingType housingTypes = 1;</code>
   */
  int getHousingTypesCount();
  /**
   * <code>repeated .dk.via.mithus.protobuf.HousingType housingTypes = 1;</code>
   */
  java.util.List<? extends dk.via.mithus.protobuf.HousingTypeOrBuilder> 
      getHousingTypesOrBuilderList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.HousingType housingTypes = 1;</code>
   */
  dk.via.mithus.protobuf.HousingTypeOrBuilder getHousingTypesOrBuilder(
      int index);
}
