// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

/**
 * Protobuf type {@code dk.via.mithus.protobuf.PostResponse}
 */
public final class PostResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dk.via.mithus.protobuf.PostResponse)
    PostResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PostResponse.newBuilder() to construct.
  private PostResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PostResponse() {
    title_ = "";
    description_ = "";
    creationDate_ = "";
    image_ = java.util.Collections.emptyList();
    amenity_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PostResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PostResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 33: {

            area_ = input.readDouble();
            break;
          }
          case 40: {

            maxTenants_ = input.readInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            creationDate_ = s;
            break;
          }
          case 58: {
            dk.via.mithus.protobuf.HousingType.Builder subBuilder = null;
            if (housingType_ != null) {
              subBuilder = housingType_.toBuilder();
            }
            housingType_ = input.readMessage(dk.via.mithus.protobuf.HousingType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(housingType_);
              housingType_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            dk.via.mithus.protobuf.EnergyRating.Builder subBuilder = null;
            if (energyRating_ != null) {
              subBuilder = energyRating_.toBuilder();
            }
            energyRating_ = input.readMessage(dk.via.mithus.protobuf.EnergyRating.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(energyRating_);
              energyRating_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            dk.via.mithus.protobuf.PostStatus.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(dk.via.mithus.protobuf.PostStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            dk.via.mithus.protobuf.User.Builder subBuilder = null;
            if (landlord_ != null) {
              subBuilder = landlord_.toBuilder();
            }
            landlord_ = input.readMessage(dk.via.mithus.protobuf.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(landlord_);
              landlord_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              image_ = new java.util.ArrayList<dk.via.mithus.protobuf.Image>();
              mutable_bitField0_ |= 0x00000001;
            }
            image_.add(
                input.readMessage(dk.via.mithus.protobuf.Image.parser(), extensionRegistry));
            break;
          }
          case 98: {
            dk.via.mithus.protobuf.Address.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(dk.via.mithus.protobuf.Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 106: {
            dk.via.mithus.protobuf.Cost.Builder subBuilder = null;
            if (cost_ != null) {
              subBuilder = cost_.toBuilder();
            }
            cost_ = input.readMessage(dk.via.mithus.protobuf.Cost.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cost_);
              cost_ = subBuilder.buildPartial();
            }

            break;
          }
          case 114: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              amenity_ = new java.util.ArrayList<dk.via.mithus.protobuf.Amenity>();
              mutable_bitField0_ |= 0x00000002;
            }
            amenity_.add(
                input.readMessage(dk.via.mithus.protobuf.Amenity.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        image_ = java.util.Collections.unmodifiableList(image_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        amenity_ = java.util.Collections.unmodifiableList(amenity_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.mithus.protobuf.PostResponse.class, dk.via.mithus.protobuf.PostResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AREA_FIELD_NUMBER = 4;
  private double area_;
  /**
   * <code>double area = 4;</code>
   * @return The area.
   */
  @java.lang.Override
  public double getArea() {
    return area_;
  }

  public static final int MAXTENANTS_FIELD_NUMBER = 5;
  private int maxTenants_;
  /**
   * <code>int32 maxTenants = 5;</code>
   * @return The maxTenants.
   */
  @java.lang.Override
  public int getMaxTenants() {
    return maxTenants_;
  }

  public static final int CREATIONDATE_FIELD_NUMBER = 6;
  private volatile java.lang.Object creationDate_;
  /**
   * <code>string creationDate = 6;</code>
   * @return The creationDate.
   */
  @java.lang.Override
  public java.lang.String getCreationDate() {
    java.lang.Object ref = creationDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creationDate_ = s;
      return s;
    }
  }
  /**
   * <code>string creationDate = 6;</code>
   * @return The bytes for creationDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreationDateBytes() {
    java.lang.Object ref = creationDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creationDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOUSINGTYPE_FIELD_NUMBER = 7;
  private dk.via.mithus.protobuf.HousingType housingType_;
  /**
   * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
   * @return Whether the housingType field is set.
   */
  @java.lang.Override
  public boolean hasHousingType() {
    return housingType_ != null;
  }
  /**
   * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
   * @return The housingType.
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.HousingType getHousingType() {
    return housingType_ == null ? dk.via.mithus.protobuf.HousingType.getDefaultInstance() : housingType_;
  }
  /**
   * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.HousingTypeOrBuilder getHousingTypeOrBuilder() {
    return getHousingType();
  }

  public static final int ENERGYRATING_FIELD_NUMBER = 8;
  private dk.via.mithus.protobuf.EnergyRating energyRating_;
  /**
   * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
   * @return Whether the energyRating field is set.
   */
  @java.lang.Override
  public boolean hasEnergyRating() {
    return energyRating_ != null;
  }
  /**
   * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
   * @return The energyRating.
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.EnergyRating getEnergyRating() {
    return energyRating_ == null ? dk.via.mithus.protobuf.EnergyRating.getDefaultInstance() : energyRating_;
  }
  /**
   * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.EnergyRatingOrBuilder getEnergyRatingOrBuilder() {
    return getEnergyRating();
  }

  public static final int STATUS_FIELD_NUMBER = 9;
  private dk.via.mithus.protobuf.PostStatus status_;
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
   * @return The status.
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.PostStatus getStatus() {
    return status_ == null ? dk.via.mithus.protobuf.PostStatus.getDefaultInstance() : status_;
  }
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.PostStatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int LANDLORD_FIELD_NUMBER = 10;
  private dk.via.mithus.protobuf.User landlord_;
  /**
   * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
   * @return Whether the landlord field is set.
   */
  @java.lang.Override
  public boolean hasLandlord() {
    return landlord_ != null;
  }
  /**
   * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
   * @return The landlord.
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.User getLandlord() {
    return landlord_ == null ? dk.via.mithus.protobuf.User.getDefaultInstance() : landlord_;
  }
  /**
   * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.UserOrBuilder getLandlordOrBuilder() {
    return getLandlord();
  }

  public static final int IMAGE_FIELD_NUMBER = 11;
  private java.util.List<dk.via.mithus.protobuf.Image> image_;
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public java.util.List<dk.via.mithus.protobuf.Image> getImageList() {
    return image_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dk.via.mithus.protobuf.ImageOrBuilder> 
      getImageOrBuilderList() {
    return image_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public int getImageCount() {
    return image_.size();
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Image getImage(int index) {
    return image_.get(index);
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.ImageOrBuilder getImageOrBuilder(
      int index) {
    return image_.get(index);
  }

  public static final int ADDRESS_FIELD_NUMBER = 12;
  private dk.via.mithus.protobuf.Address address_;
  /**
   * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
   * @return The address.
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Address getAddress() {
    return address_ == null ? dk.via.mithus.protobuf.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.AddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int COST_FIELD_NUMBER = 13;
  private dk.via.mithus.protobuf.Cost cost_;
  /**
   * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
   * @return Whether the cost field is set.
   */
  @java.lang.Override
  public boolean hasCost() {
    return cost_ != null;
  }
  /**
   * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
   * @return The cost.
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Cost getCost() {
    return cost_ == null ? dk.via.mithus.protobuf.Cost.getDefaultInstance() : cost_;
  }
  /**
   * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.CostOrBuilder getCostOrBuilder() {
    return getCost();
  }

  public static final int AMENITY_FIELD_NUMBER = 14;
  private java.util.List<dk.via.mithus.protobuf.Amenity> amenity_;
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public java.util.List<dk.via.mithus.protobuf.Amenity> getAmenityList() {
    return amenity_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dk.via.mithus.protobuf.AmenityOrBuilder> 
      getAmenityOrBuilderList() {
    return amenity_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public int getAmenityCount() {
    return amenity_.size();
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Amenity getAmenity(int index) {
    return amenity_.get(index);
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.AmenityOrBuilder getAmenityOrBuilder(
      int index) {
    return amenity_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (java.lang.Double.doubleToRawLongBits(area_) != 0) {
      output.writeDouble(4, area_);
    }
    if (maxTenants_ != 0) {
      output.writeInt32(5, maxTenants_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creationDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, creationDate_);
    }
    if (housingType_ != null) {
      output.writeMessage(7, getHousingType());
    }
    if (energyRating_ != null) {
      output.writeMessage(8, getEnergyRating());
    }
    if (status_ != null) {
      output.writeMessage(9, getStatus());
    }
    if (landlord_ != null) {
      output.writeMessage(10, getLandlord());
    }
    for (int i = 0; i < image_.size(); i++) {
      output.writeMessage(11, image_.get(i));
    }
    if (address_ != null) {
      output.writeMessage(12, getAddress());
    }
    if (cost_ != null) {
      output.writeMessage(13, getCost());
    }
    for (int i = 0; i < amenity_.size(); i++) {
      output.writeMessage(14, amenity_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (java.lang.Double.doubleToRawLongBits(area_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, area_);
    }
    if (maxTenants_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxTenants_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creationDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, creationDate_);
    }
    if (housingType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getHousingType());
    }
    if (energyRating_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getEnergyRating());
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getStatus());
    }
    if (landlord_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getLandlord());
    }
    for (int i = 0; i < image_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, image_.get(i));
    }
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getAddress());
    }
    if (cost_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getCost());
    }
    for (int i = 0; i < amenity_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, amenity_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.mithus.protobuf.PostResponse)) {
      return super.equals(obj);
    }
    dk.via.mithus.protobuf.PostResponse other = (dk.via.mithus.protobuf.PostResponse) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (java.lang.Double.doubleToLongBits(getArea())
        != java.lang.Double.doubleToLongBits(
            other.getArea())) return false;
    if (getMaxTenants()
        != other.getMaxTenants()) return false;
    if (!getCreationDate()
        .equals(other.getCreationDate())) return false;
    if (hasHousingType() != other.hasHousingType()) return false;
    if (hasHousingType()) {
      if (!getHousingType()
          .equals(other.getHousingType())) return false;
    }
    if (hasEnergyRating() != other.hasEnergyRating()) return false;
    if (hasEnergyRating()) {
      if (!getEnergyRating()
          .equals(other.getEnergyRating())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasLandlord() != other.hasLandlord()) return false;
    if (hasLandlord()) {
      if (!getLandlord()
          .equals(other.getLandlord())) return false;
    }
    if (!getImageList()
        .equals(other.getImageList())) return false;
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (hasCost() != other.hasCost()) return false;
    if (hasCost()) {
      if (!getCost()
          .equals(other.getCost())) return false;
    }
    if (!getAmenityList()
        .equals(other.getAmenityList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + AREA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getArea()));
    hash = (37 * hash) + MAXTENANTS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxTenants();
    hash = (37 * hash) + CREATIONDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCreationDate().hashCode();
    if (hasHousingType()) {
      hash = (37 * hash) + HOUSINGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getHousingType().hashCode();
    }
    if (hasEnergyRating()) {
      hash = (37 * hash) + ENERGYRATING_FIELD_NUMBER;
      hash = (53 * hash) + getEnergyRating().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasLandlord()) {
      hash = (37 * hash) + LANDLORD_FIELD_NUMBER;
      hash = (53 * hash) + getLandlord().hashCode();
    }
    if (getImageCount() > 0) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImageList().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (hasCost()) {
      hash = (37 * hash) + COST_FIELD_NUMBER;
      hash = (53 * hash) + getCost().hashCode();
    }
    if (getAmenityCount() > 0) {
      hash = (37 * hash) + AMENITY_FIELD_NUMBER;
      hash = (53 * hash) + getAmenityList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.mithus.protobuf.PostResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.PostResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.PostResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.mithus.protobuf.PostResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dk.via.mithus.protobuf.PostResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dk.via.mithus.protobuf.PostResponse)
      dk.via.mithus.protobuf.PostResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.mithus.protobuf.PostResponse.class, dk.via.mithus.protobuf.PostResponse.Builder.class);
    }

    // Construct using dk.via.mithus.protobuf.PostResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImageFieldBuilder();
        getAmenityFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      title_ = "";

      description_ = "";

      area_ = 0D;

      maxTenants_ = 0;

      creationDate_ = "";

      if (housingTypeBuilder_ == null) {
        housingType_ = null;
      } else {
        housingType_ = null;
        housingTypeBuilder_ = null;
      }
      if (energyRatingBuilder_ == null) {
        energyRating_ = null;
      } else {
        energyRating_ = null;
        energyRatingBuilder_ = null;
      }
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (landlordBuilder_ == null) {
        landlord_ = null;
      } else {
        landlord_ = null;
        landlordBuilder_ = null;
      }
      if (imageBuilder_ == null) {
        image_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        imageBuilder_.clear();
      }
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      if (costBuilder_ == null) {
        cost_ = null;
      } else {
        cost_ = null;
        costBuilder_ = null;
      }
      if (amenityBuilder_ == null) {
        amenity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        amenityBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_PostResponse_descriptor;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.PostResponse getDefaultInstanceForType() {
      return dk.via.mithus.protobuf.PostResponse.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.PostResponse build() {
      dk.via.mithus.protobuf.PostResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.PostResponse buildPartial() {
      dk.via.mithus.protobuf.PostResponse result = new dk.via.mithus.protobuf.PostResponse(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.title_ = title_;
      result.description_ = description_;
      result.area_ = area_;
      result.maxTenants_ = maxTenants_;
      result.creationDate_ = creationDate_;
      if (housingTypeBuilder_ == null) {
        result.housingType_ = housingType_;
      } else {
        result.housingType_ = housingTypeBuilder_.build();
      }
      if (energyRatingBuilder_ == null) {
        result.energyRating_ = energyRating_;
      } else {
        result.energyRating_ = energyRatingBuilder_.build();
      }
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (landlordBuilder_ == null) {
        result.landlord_ = landlord_;
      } else {
        result.landlord_ = landlordBuilder_.build();
      }
      if (imageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          image_ = java.util.Collections.unmodifiableList(image_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.image_ = image_;
      } else {
        result.image_ = imageBuilder_.build();
      }
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      if (costBuilder_ == null) {
        result.cost_ = cost_;
      } else {
        result.cost_ = costBuilder_.build();
      }
      if (amenityBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          amenity_ = java.util.Collections.unmodifiableList(amenity_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.amenity_ = amenity_;
      } else {
        result.amenity_ = amenityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.mithus.protobuf.PostResponse) {
        return mergeFrom((dk.via.mithus.protobuf.PostResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.mithus.protobuf.PostResponse other) {
      if (other == dk.via.mithus.protobuf.PostResponse.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getArea() != 0D) {
        setArea(other.getArea());
      }
      if (other.getMaxTenants() != 0) {
        setMaxTenants(other.getMaxTenants());
      }
      if (!other.getCreationDate().isEmpty()) {
        creationDate_ = other.creationDate_;
        onChanged();
      }
      if (other.hasHousingType()) {
        mergeHousingType(other.getHousingType());
      }
      if (other.hasEnergyRating()) {
        mergeEnergyRating(other.getEnergyRating());
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasLandlord()) {
        mergeLandlord(other.getLandlord());
      }
      if (imageBuilder_ == null) {
        if (!other.image_.isEmpty()) {
          if (image_.isEmpty()) {
            image_ = other.image_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImageIsMutable();
            image_.addAll(other.image_);
          }
          onChanged();
        }
      } else {
        if (!other.image_.isEmpty()) {
          if (imageBuilder_.isEmpty()) {
            imageBuilder_.dispose();
            imageBuilder_ = null;
            image_ = other.image_;
            bitField0_ = (bitField0_ & ~0x00000001);
            imageBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getImageFieldBuilder() : null;
          } else {
            imageBuilder_.addAllMessages(other.image_);
          }
        }
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.hasCost()) {
        mergeCost(other.getCost());
      }
      if (amenityBuilder_ == null) {
        if (!other.amenity_.isEmpty()) {
          if (amenity_.isEmpty()) {
            amenity_ = other.amenity_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAmenityIsMutable();
            amenity_.addAll(other.amenity_);
          }
          onChanged();
        }
      } else {
        if (!other.amenity_.isEmpty()) {
          if (amenityBuilder_.isEmpty()) {
            amenityBuilder_.dispose();
            amenityBuilder_ = null;
            amenity_ = other.amenity_;
            bitField0_ = (bitField0_ & ~0x00000002);
            amenityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAmenityFieldBuilder() : null;
          } else {
            amenityBuilder_.addAllMessages(other.amenity_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.mithus.protobuf.PostResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.mithus.protobuf.PostResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private double area_ ;
    /**
     * <code>double area = 4;</code>
     * @return The area.
     */
    @java.lang.Override
    public double getArea() {
      return area_;
    }
    /**
     * <code>double area = 4;</code>
     * @param value The area to set.
     * @return This builder for chaining.
     */
    public Builder setArea(double value) {
      
      area_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double area = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearArea() {
      
      area_ = 0D;
      onChanged();
      return this;
    }

    private int maxTenants_ ;
    /**
     * <code>int32 maxTenants = 5;</code>
     * @return The maxTenants.
     */
    @java.lang.Override
    public int getMaxTenants() {
      return maxTenants_;
    }
    /**
     * <code>int32 maxTenants = 5;</code>
     * @param value The maxTenants to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTenants(int value) {
      
      maxTenants_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxTenants = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTenants() {
      
      maxTenants_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object creationDate_ = "";
    /**
     * <code>string creationDate = 6;</code>
     * @return The creationDate.
     */
    public java.lang.String getCreationDate() {
      java.lang.Object ref = creationDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creationDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string creationDate = 6;</code>
     * @return The bytes for creationDate.
     */
    public com.google.protobuf.ByteString
        getCreationDateBytes() {
      java.lang.Object ref = creationDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string creationDate = 6;</code>
     * @param value The creationDate to set.
     * @return This builder for chaining.
     */
    public Builder setCreationDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creationDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string creationDate = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreationDate() {
      
      creationDate_ = getDefaultInstance().getCreationDate();
      onChanged();
      return this;
    }
    /**
     * <code>string creationDate = 6;</code>
     * @param value The bytes for creationDate to set.
     * @return This builder for chaining.
     */
    public Builder setCreationDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creationDate_ = value;
      onChanged();
      return this;
    }

    private dk.via.mithus.protobuf.HousingType housingType_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.HousingType, dk.via.mithus.protobuf.HousingType.Builder, dk.via.mithus.protobuf.HousingTypeOrBuilder> housingTypeBuilder_;
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     * @return Whether the housingType field is set.
     */
    public boolean hasHousingType() {
      return housingTypeBuilder_ != null || housingType_ != null;
    }
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     * @return The housingType.
     */
    public dk.via.mithus.protobuf.HousingType getHousingType() {
      if (housingTypeBuilder_ == null) {
        return housingType_ == null ? dk.via.mithus.protobuf.HousingType.getDefaultInstance() : housingType_;
      } else {
        return housingTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     */
    public Builder setHousingType(dk.via.mithus.protobuf.HousingType value) {
      if (housingTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        housingType_ = value;
        onChanged();
      } else {
        housingTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     */
    public Builder setHousingType(
        dk.via.mithus.protobuf.HousingType.Builder builderForValue) {
      if (housingTypeBuilder_ == null) {
        housingType_ = builderForValue.build();
        onChanged();
      } else {
        housingTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     */
    public Builder mergeHousingType(dk.via.mithus.protobuf.HousingType value) {
      if (housingTypeBuilder_ == null) {
        if (housingType_ != null) {
          housingType_ =
            dk.via.mithus.protobuf.HousingType.newBuilder(housingType_).mergeFrom(value).buildPartial();
        } else {
          housingType_ = value;
        }
        onChanged();
      } else {
        housingTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     */
    public Builder clearHousingType() {
      if (housingTypeBuilder_ == null) {
        housingType_ = null;
        onChanged();
      } else {
        housingType_ = null;
        housingTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     */
    public dk.via.mithus.protobuf.HousingType.Builder getHousingTypeBuilder() {
      
      onChanged();
      return getHousingTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     */
    public dk.via.mithus.protobuf.HousingTypeOrBuilder getHousingTypeOrBuilder() {
      if (housingTypeBuilder_ != null) {
        return housingTypeBuilder_.getMessageOrBuilder();
      } else {
        return housingType_ == null ?
            dk.via.mithus.protobuf.HousingType.getDefaultInstance() : housingType_;
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.HousingType housingType = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.HousingType, dk.via.mithus.protobuf.HousingType.Builder, dk.via.mithus.protobuf.HousingTypeOrBuilder> 
        getHousingTypeFieldBuilder() {
      if (housingTypeBuilder_ == null) {
        housingTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.mithus.protobuf.HousingType, dk.via.mithus.protobuf.HousingType.Builder, dk.via.mithus.protobuf.HousingTypeOrBuilder>(
                getHousingType(),
                getParentForChildren(),
                isClean());
        housingType_ = null;
      }
      return housingTypeBuilder_;
    }

    private dk.via.mithus.protobuf.EnergyRating energyRating_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.EnergyRating, dk.via.mithus.protobuf.EnergyRating.Builder, dk.via.mithus.protobuf.EnergyRatingOrBuilder> energyRatingBuilder_;
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     * @return Whether the energyRating field is set.
     */
    public boolean hasEnergyRating() {
      return energyRatingBuilder_ != null || energyRating_ != null;
    }
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     * @return The energyRating.
     */
    public dk.via.mithus.protobuf.EnergyRating getEnergyRating() {
      if (energyRatingBuilder_ == null) {
        return energyRating_ == null ? dk.via.mithus.protobuf.EnergyRating.getDefaultInstance() : energyRating_;
      } else {
        return energyRatingBuilder_.getMessage();
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     */
    public Builder setEnergyRating(dk.via.mithus.protobuf.EnergyRating value) {
      if (energyRatingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        energyRating_ = value;
        onChanged();
      } else {
        energyRatingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     */
    public Builder setEnergyRating(
        dk.via.mithus.protobuf.EnergyRating.Builder builderForValue) {
      if (energyRatingBuilder_ == null) {
        energyRating_ = builderForValue.build();
        onChanged();
      } else {
        energyRatingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     */
    public Builder mergeEnergyRating(dk.via.mithus.protobuf.EnergyRating value) {
      if (energyRatingBuilder_ == null) {
        if (energyRating_ != null) {
          energyRating_ =
            dk.via.mithus.protobuf.EnergyRating.newBuilder(energyRating_).mergeFrom(value).buildPartial();
        } else {
          energyRating_ = value;
        }
        onChanged();
      } else {
        energyRatingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     */
    public Builder clearEnergyRating() {
      if (energyRatingBuilder_ == null) {
        energyRating_ = null;
        onChanged();
      } else {
        energyRating_ = null;
        energyRatingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     */
    public dk.via.mithus.protobuf.EnergyRating.Builder getEnergyRatingBuilder() {
      
      onChanged();
      return getEnergyRatingFieldBuilder().getBuilder();
    }
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     */
    public dk.via.mithus.protobuf.EnergyRatingOrBuilder getEnergyRatingOrBuilder() {
      if (energyRatingBuilder_ != null) {
        return energyRatingBuilder_.getMessageOrBuilder();
      } else {
        return energyRating_ == null ?
            dk.via.mithus.protobuf.EnergyRating.getDefaultInstance() : energyRating_;
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.EnergyRating energyRating = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.EnergyRating, dk.via.mithus.protobuf.EnergyRating.Builder, dk.via.mithus.protobuf.EnergyRatingOrBuilder> 
        getEnergyRatingFieldBuilder() {
      if (energyRatingBuilder_ == null) {
        energyRatingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.mithus.protobuf.EnergyRating, dk.via.mithus.protobuf.EnergyRating.Builder, dk.via.mithus.protobuf.EnergyRatingOrBuilder>(
                getEnergyRating(),
                getParentForChildren(),
                isClean());
        energyRating_ = null;
      }
      return energyRatingBuilder_;
    }

    private dk.via.mithus.protobuf.PostStatus status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.PostStatus, dk.via.mithus.protobuf.PostStatus.Builder, dk.via.mithus.protobuf.PostStatusOrBuilder> statusBuilder_;
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     * @return The status.
     */
    public dk.via.mithus.protobuf.PostStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? dk.via.mithus.protobuf.PostStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     */
    public Builder setStatus(dk.via.mithus.protobuf.PostStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     */
    public Builder setStatus(
        dk.via.mithus.protobuf.PostStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     */
    public Builder mergeStatus(dk.via.mithus.protobuf.PostStatus value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            dk.via.mithus.protobuf.PostStatus.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     */
    public dk.via.mithus.protobuf.PostStatus.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     */
    public dk.via.mithus.protobuf.PostStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            dk.via.mithus.protobuf.PostStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.PostStatus status = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.PostStatus, dk.via.mithus.protobuf.PostStatus.Builder, dk.via.mithus.protobuf.PostStatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.mithus.protobuf.PostStatus, dk.via.mithus.protobuf.PostStatus.Builder, dk.via.mithus.protobuf.PostStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private dk.via.mithus.protobuf.User landlord_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.User, dk.via.mithus.protobuf.User.Builder, dk.via.mithus.protobuf.UserOrBuilder> landlordBuilder_;
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     * @return Whether the landlord field is set.
     */
    public boolean hasLandlord() {
      return landlordBuilder_ != null || landlord_ != null;
    }
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     * @return The landlord.
     */
    public dk.via.mithus.protobuf.User getLandlord() {
      if (landlordBuilder_ == null) {
        return landlord_ == null ? dk.via.mithus.protobuf.User.getDefaultInstance() : landlord_;
      } else {
        return landlordBuilder_.getMessage();
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     */
    public Builder setLandlord(dk.via.mithus.protobuf.User value) {
      if (landlordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        landlord_ = value;
        onChanged();
      } else {
        landlordBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     */
    public Builder setLandlord(
        dk.via.mithus.protobuf.User.Builder builderForValue) {
      if (landlordBuilder_ == null) {
        landlord_ = builderForValue.build();
        onChanged();
      } else {
        landlordBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     */
    public Builder mergeLandlord(dk.via.mithus.protobuf.User value) {
      if (landlordBuilder_ == null) {
        if (landlord_ != null) {
          landlord_ =
            dk.via.mithus.protobuf.User.newBuilder(landlord_).mergeFrom(value).buildPartial();
        } else {
          landlord_ = value;
        }
        onChanged();
      } else {
        landlordBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     */
    public Builder clearLandlord() {
      if (landlordBuilder_ == null) {
        landlord_ = null;
        onChanged();
      } else {
        landlord_ = null;
        landlordBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     */
    public dk.via.mithus.protobuf.User.Builder getLandlordBuilder() {
      
      onChanged();
      return getLandlordFieldBuilder().getBuilder();
    }
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     */
    public dk.via.mithus.protobuf.UserOrBuilder getLandlordOrBuilder() {
      if (landlordBuilder_ != null) {
        return landlordBuilder_.getMessageOrBuilder();
      } else {
        return landlord_ == null ?
            dk.via.mithus.protobuf.User.getDefaultInstance() : landlord_;
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.User landlord = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.User, dk.via.mithus.protobuf.User.Builder, dk.via.mithus.protobuf.UserOrBuilder> 
        getLandlordFieldBuilder() {
      if (landlordBuilder_ == null) {
        landlordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.mithus.protobuf.User, dk.via.mithus.protobuf.User.Builder, dk.via.mithus.protobuf.UserOrBuilder>(
                getLandlord(),
                getParentForChildren(),
                isClean());
        landlord_ = null;
      }
      return landlordBuilder_;
    }

    private java.util.List<dk.via.mithus.protobuf.Image> image_ =
      java.util.Collections.emptyList();
    private void ensureImageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        image_ = new java.util.ArrayList<dk.via.mithus.protobuf.Image>(image_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder> imageBuilder_;

    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Image> getImageList() {
      if (imageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(image_);
      } else {
        return imageBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public int getImageCount() {
      if (imageBuilder_ == null) {
        return image_.size();
      } else {
        return imageBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.Image getImage(int index) {
      if (imageBuilder_ == null) {
        return image_.get(index);
      } else {
        return imageBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder setImage(
        int index, dk.via.mithus.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.set(index, value);
        onChanged();
      } else {
        imageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder setImage(
        int index, dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.set(index, builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addImage(dk.via.mithus.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.add(value);
        onChanged();
      } else {
        imageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addImage(
        int index, dk.via.mithus.protobuf.Image value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImageIsMutable();
        image_.add(index, value);
        onChanged();
      } else {
        imageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addImage(
        dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.add(builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addImage(
        int index, dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.add(index, builderForValue.build());
        onChanged();
      } else {
        imageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder addAllImage(
        java.lang.Iterable<? extends dk.via.mithus.protobuf.Image> values) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, image_);
        onChanged();
      } else {
        imageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder clearImage() {
      if (imageBuilder_ == null) {
        image_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        imageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public Builder removeImage(int index) {
      if (imageBuilder_ == null) {
        ensureImageIsMutable();
        image_.remove(index);
        onChanged();
      } else {
        imageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder getImageBuilder(
        int index) {
      return getImageFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.ImageOrBuilder getImageOrBuilder(
        int index) {
      if (imageBuilder_ == null) {
        return image_.get(index);  } else {
        return imageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public java.util.List<? extends dk.via.mithus.protobuf.ImageOrBuilder> 
         getImageOrBuilderList() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(image_);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder addImageBuilder() {
      return getImageFieldBuilder().addBuilder(
          dk.via.mithus.protobuf.Image.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder addImageBuilder(
        int index) {
      return getImageFieldBuilder().addBuilder(
          index, dk.via.mithus.protobuf.Image.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image image = 11;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Image.Builder> 
         getImageBuilderList() {
      return getImageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder>(
                image_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }

    private dk.via.mithus.protobuf.Address address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.Address, dk.via.mithus.protobuf.Address.Builder, dk.via.mithus.protobuf.AddressOrBuilder> addressBuilder_;
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     * @return The address.
     */
    public dk.via.mithus.protobuf.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? dk.via.mithus.protobuf.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public Builder setAddress(dk.via.mithus.protobuf.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public Builder setAddress(
        dk.via.mithus.protobuf.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public Builder mergeAddress(dk.via.mithus.protobuf.Address value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            dk.via.mithus.protobuf.Address.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public dk.via.mithus.protobuf.Address.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    public dk.via.mithus.protobuf.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            dk.via.mithus.protobuf.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.Address address = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.Address, dk.via.mithus.protobuf.Address.Builder, dk.via.mithus.protobuf.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.mithus.protobuf.Address, dk.via.mithus.protobuf.Address.Builder, dk.via.mithus.protobuf.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private dk.via.mithus.protobuf.Cost cost_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.Cost, dk.via.mithus.protobuf.Cost.Builder, dk.via.mithus.protobuf.CostOrBuilder> costBuilder_;
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     * @return Whether the cost field is set.
     */
    public boolean hasCost() {
      return costBuilder_ != null || cost_ != null;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     * @return The cost.
     */
    public dk.via.mithus.protobuf.Cost getCost() {
      if (costBuilder_ == null) {
        return cost_ == null ? dk.via.mithus.protobuf.Cost.getDefaultInstance() : cost_;
      } else {
        return costBuilder_.getMessage();
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public Builder setCost(dk.via.mithus.protobuf.Cost value) {
      if (costBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cost_ = value;
        onChanged();
      } else {
        costBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public Builder setCost(
        dk.via.mithus.protobuf.Cost.Builder builderForValue) {
      if (costBuilder_ == null) {
        cost_ = builderForValue.build();
        onChanged();
      } else {
        costBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public Builder mergeCost(dk.via.mithus.protobuf.Cost value) {
      if (costBuilder_ == null) {
        if (cost_ != null) {
          cost_ =
            dk.via.mithus.protobuf.Cost.newBuilder(cost_).mergeFrom(value).buildPartial();
        } else {
          cost_ = value;
        }
        onChanged();
      } else {
        costBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public Builder clearCost() {
      if (costBuilder_ == null) {
        cost_ = null;
        onChanged();
      } else {
        cost_ = null;
        costBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public dk.via.mithus.protobuf.Cost.Builder getCostBuilder() {
      
      onChanged();
      return getCostFieldBuilder().getBuilder();
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    public dk.via.mithus.protobuf.CostOrBuilder getCostOrBuilder() {
      if (costBuilder_ != null) {
        return costBuilder_.getMessageOrBuilder();
      } else {
        return cost_ == null ?
            dk.via.mithus.protobuf.Cost.getDefaultInstance() : cost_;
      }
    }
    /**
     * <code>.dk.via.mithus.protobuf.Cost cost = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dk.via.mithus.protobuf.Cost, dk.via.mithus.protobuf.Cost.Builder, dk.via.mithus.protobuf.CostOrBuilder> 
        getCostFieldBuilder() {
      if (costBuilder_ == null) {
        costBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dk.via.mithus.protobuf.Cost, dk.via.mithus.protobuf.Cost.Builder, dk.via.mithus.protobuf.CostOrBuilder>(
                getCost(),
                getParentForChildren(),
                isClean());
        cost_ = null;
      }
      return costBuilder_;
    }

    private java.util.List<dk.via.mithus.protobuf.Amenity> amenity_ =
      java.util.Collections.emptyList();
    private void ensureAmenityIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        amenity_ = new java.util.ArrayList<dk.via.mithus.protobuf.Amenity>(amenity_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Amenity, dk.via.mithus.protobuf.Amenity.Builder, dk.via.mithus.protobuf.AmenityOrBuilder> amenityBuilder_;

    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Amenity> getAmenityList() {
      if (amenityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(amenity_);
      } else {
        return amenityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public int getAmenityCount() {
      if (amenityBuilder_ == null) {
        return amenity_.size();
      } else {
        return amenityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.Amenity getAmenity(int index) {
      if (amenityBuilder_ == null) {
        return amenity_.get(index);
      } else {
        return amenityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder setAmenity(
        int index, dk.via.mithus.protobuf.Amenity value) {
      if (amenityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmenityIsMutable();
        amenity_.set(index, value);
        onChanged();
      } else {
        amenityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder setAmenity(
        int index, dk.via.mithus.protobuf.Amenity.Builder builderForValue) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        amenity_.set(index, builderForValue.build());
        onChanged();
      } else {
        amenityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAmenity(dk.via.mithus.protobuf.Amenity value) {
      if (amenityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmenityIsMutable();
        amenity_.add(value);
        onChanged();
      } else {
        amenityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAmenity(
        int index, dk.via.mithus.protobuf.Amenity value) {
      if (amenityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAmenityIsMutable();
        amenity_.add(index, value);
        onChanged();
      } else {
        amenityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAmenity(
        dk.via.mithus.protobuf.Amenity.Builder builderForValue) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        amenity_.add(builderForValue.build());
        onChanged();
      } else {
        amenityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAmenity(
        int index, dk.via.mithus.protobuf.Amenity.Builder builderForValue) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        amenity_.add(index, builderForValue.build());
        onChanged();
      } else {
        amenityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder addAllAmenity(
        java.lang.Iterable<? extends dk.via.mithus.protobuf.Amenity> values) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, amenity_);
        onChanged();
      } else {
        amenityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder clearAmenity() {
      if (amenityBuilder_ == null) {
        amenity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        amenityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public Builder removeAmenity(int index) {
      if (amenityBuilder_ == null) {
        ensureAmenityIsMutable();
        amenity_.remove(index);
        onChanged();
      } else {
        amenityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.Amenity.Builder getAmenityBuilder(
        int index) {
      return getAmenityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.AmenityOrBuilder getAmenityOrBuilder(
        int index) {
      if (amenityBuilder_ == null) {
        return amenity_.get(index);  } else {
        return amenityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public java.util.List<? extends dk.via.mithus.protobuf.AmenityOrBuilder> 
         getAmenityOrBuilderList() {
      if (amenityBuilder_ != null) {
        return amenityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(amenity_);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.Amenity.Builder addAmenityBuilder() {
      return getAmenityFieldBuilder().addBuilder(
          dk.via.mithus.protobuf.Amenity.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public dk.via.mithus.protobuf.Amenity.Builder addAmenityBuilder(
        int index) {
      return getAmenityFieldBuilder().addBuilder(
          index, dk.via.mithus.protobuf.Amenity.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Amenity amenity = 14;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Amenity.Builder> 
         getAmenityBuilderList() {
      return getAmenityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Amenity, dk.via.mithus.protobuf.Amenity.Builder, dk.via.mithus.protobuf.AmenityOrBuilder> 
        getAmenityFieldBuilder() {
      if (amenityBuilder_ == null) {
        amenityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.via.mithus.protobuf.Amenity, dk.via.mithus.protobuf.Amenity.Builder, dk.via.mithus.protobuf.AmenityOrBuilder>(
                amenity_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        amenity_ = null;
      }
      return amenityBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dk.via.mithus.protobuf.PostResponse)
  }

  // @@protoc_insertion_point(class_scope:dk.via.mithus.protobuf.PostResponse)
  private static final dk.via.mithus.protobuf.PostResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.mithus.protobuf.PostResponse();
  }

  public static dk.via.mithus.protobuf.PostResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PostResponse>
      PARSER = new com.google.protobuf.AbstractParser<PostResponse>() {
    @java.lang.Override
    public PostResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PostResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PostResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PostResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.mithus.protobuf.PostResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

