// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface PostsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.Posts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dk.via.mithus.protobuf.PostCreation posts = 1;</code>
   */
  java.util.List<dk.via.mithus.protobuf.PostCreation> 
      getPostsList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.PostCreation posts = 1;</code>
   */
  dk.via.mithus.protobuf.PostCreation getPosts(int index);
  /**
   * <code>repeated .dk.via.mithus.protobuf.PostCreation posts = 1;</code>
   */
  int getPostsCount();
  /**
   * <code>repeated .dk.via.mithus.protobuf.PostCreation posts = 1;</code>
   */
  java.util.List<? extends dk.via.mithus.protobuf.PostCreationOrBuilder> 
      getPostsOrBuilderList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.PostCreation posts = 1;</code>
   */
  dk.via.mithus.protobuf.PostCreationOrBuilder getPostsOrBuilder(
      int index);
}
