// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface PostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.Post)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double area = 4;</code>
   * @return The area.
   */
  double getArea();

  /**
   * <code>int32 maxTenants = 5;</code>
   * @return The maxTenants.
   */
  int getMaxTenants();

  /**
   * <code>string creationDate = 6;</code>
   * @return The creationDate.
   */
  java.lang.String getCreationDate();
  /**
   * <code>string creationDate = 6;</code>
   * @return The bytes for creationDate.
   */
  com.google.protobuf.ByteString
      getCreationDateBytes();

  /**
   * <code>string typeId = 7;</code>
   * @return The typeId.
   */
  java.lang.String getTypeId();
  /**
   * <code>string typeId = 7;</code>
   * @return The bytes for typeId.
   */
  com.google.protobuf.ByteString
      getTypeIdBytes();

  /**
   * <code>string energyRatingId = 8;</code>
   * @return The energyRatingId.
   */
  java.lang.String getEnergyRatingId();
  /**
   * <code>string energyRatingId = 8;</code>
   * @return The bytes for energyRatingId.
   */
  com.google.protobuf.ByteString
      getEnergyRatingIdBytes();

  /**
   * <code>string statusId = 9;</code>
   * @return The statusId.
   */
  java.lang.String getStatusId();
  /**
   * <code>string statusId = 9;</code>
   * @return The bytes for statusId.
   */
  com.google.protobuf.ByteString
      getStatusIdBytes();

  /**
   * <code>string landlordId = 10;</code>
   * @return The landlordId.
   */
  java.lang.String getLandlordId();
  /**
   * <code>string landlordId = 10;</code>
   * @return The bytes for landlordId.
   */
  com.google.protobuf.ByteString
      getLandlordIdBytes();

  /**
   * <code>repeated string imageId = 11;</code>
   * @return A list containing the imageId.
   */
  java.util.List<java.lang.String>
      getImageIdList();
  /**
   * <code>repeated string imageId = 11;</code>
   * @return The count of imageId.
   */
  int getImageIdCount();
  /**
   * <code>repeated string imageId = 11;</code>
   * @param index The index of the element to return.
   * @return The imageId at the given index.
   */
  java.lang.String getImageId(int index);
  /**
   * <code>repeated string imageId = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the imageId at the given index.
   */
  com.google.protobuf.ByteString
      getImageIdBytes(int index);

  /**
   * <code>string addressId = 12;</code>
   * @return The addressId.
   */
  java.lang.String getAddressId();
  /**
   * <code>string addressId = 12;</code>
   * @return The bytes for addressId.
   */
  com.google.protobuf.ByteString
      getAddressIdBytes();

  /**
   * <code>string costId = 13;</code>
   * @return The costId.
   */
  java.lang.String getCostId();
  /**
   * <code>string costId = 13;</code>
   * @return The bytes for costId.
   */
  com.google.protobuf.ByteString
      getCostIdBytes();

  /**
   * <code>repeated string amenityId = 14;</code>
   * @return A list containing the amenityId.
   */
  java.util.List<java.lang.String>
      getAmenityIdList();
  /**
   * <code>repeated string amenityId = 14;</code>
   * @return The count of amenityId.
   */
  int getAmenityIdCount();
  /**
   * <code>repeated string amenityId = 14;</code>
   * @param index The index of the element to return.
   * @return The amenityId at the given index.
   */
  java.lang.String getAmenityId(int index);
  /**
   * <code>repeated string amenityId = 14;</code>
   * @param index The index of the value to return.
   * @return The bytes of the amenityId at the given index.
   */
  com.google.protobuf.ByteString
      getAmenityIdBytes(int index);
}
