// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface PostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.Post)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string street = 4;</code>
   * @return The street.
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 4;</code>
   * @return The bytes for street.
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>double area = 5;</code>
   * @return The area.
   */
  double getArea();

  /**
   * <code>int32 maxTenants = 6;</code>
   * @return The maxTenants.
   */
  int getMaxTenants();

  /**
   * <code>string energyRating = 7;</code>
   * @return The energyRating.
   */
  java.lang.String getEnergyRating();
  /**
   * <code>string energyRating = 7;</code>
   * @return The bytes for energyRating.
   */
  com.google.protobuf.ByteString
      getEnergyRatingBytes();

  /**
   * <code>double deposit = 8;</code>
   * @return The deposit.
   */
  double getDeposit();

  /**
   * <code>double moveInPrice = 9;</code>
   * @return The moveInPrice.
   */
  double getMoveInPrice();

  /**
   * <code>double utilities = 10;</code>
   * @return The utilities.
   */
  double getUtilities();

  /**
   * <code>bool isFurnished = 11;</code>
   * @return The isFurnished.
   */
  boolean getIsFurnished();

  /**
   * <code>bool hasBalcony = 12;</code>
   * @return The hasBalcony.
   */
  boolean getHasBalcony();

  /**
   * <code>bool smokingAllowed = 13;</code>
   * @return The smokingAllowed.
   */
  boolean getSmokingAllowed();

  /**
   * <code>bool hasParking = 14;</code>
   * @return The hasParking.
   */
  boolean getHasParking();

  /**
   * <code>bool hasDryer = 15;</code>
   * @return The hasDryer.
   */
  boolean getHasDryer();

  /**
   * <code>bool hasMonthlyRent = 16;</code>
   * @return The hasMonthlyRent.
   */
  boolean getHasMonthlyRent();

  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 17;</code>
   */
  java.util.List<dk.via.mithus.protobuf.Image> 
      getImagesList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 17;</code>
   */
  dk.via.mithus.protobuf.Image getImages(int index);
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 17;</code>
   */
  int getImagesCount();
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 17;</code>
   */
  java.util.List<? extends dk.via.mithus.protobuf.ImageOrBuilder> 
      getImagesOrBuilderList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 17;</code>
   */
  dk.via.mithus.protobuf.ImageOrBuilder getImagesOrBuilder(
      int index);

  /**
   * <code>string userId = 18;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 18;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
