// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

/**
 * Protobuf type {@code dk.via.mithus.protobuf.Post}
 */
public final class Post extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dk.via.mithus.protobuf.Post)
    PostOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Post.newBuilder() to construct.
  private Post(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Post() {
    id_ = "";
    title_ = "";
    description_ = "";
    street_ = "";
    type_ = "";
    energyRating_ = "";
    status_ = "";
    images_ = java.util.Collections.emptyList();
    userId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Post();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Post(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            street_ = s;
            break;
          }
          case 41: {

            area_ = input.readDouble();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 56: {

            maxTenants_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            energyRating_ = s;
            break;
          }
          case 73: {

            deposit_ = input.readDouble();
            break;
          }
          case 81: {

            moveInPrice_ = input.readDouble();
            break;
          }
          case 89: {

            utilities_ = input.readDouble();
            break;
          }
          case 97: {

            monthlyRent_ = input.readDouble();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 112: {

            isFurnished_ = input.readBool();
            break;
          }
          case 120: {

            hasBalcony_ = input.readBool();
            break;
          }
          case 128: {

            smokingAllowed_ = input.readBool();
            break;
          }
          case 136: {

            hasParking_ = input.readBool();
            break;
          }
          case 144: {

            hasDryer_ = input.readBool();
            break;
          }
          case 152: {

            hasDishwasher_ = input.readBool();
            break;
          }
          case 160: {

            hasWashingMachine_ = input.readBool();
            break;
          }
          case 170: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              images_ = new java.util.ArrayList<dk.via.mithus.protobuf.Image>();
              mutable_bitField0_ |= 0x00000001;
            }
            images_.add(
                input.readMessage(dk.via.mithus.protobuf.Image.parser(), extensionRegistry));
            break;
          }
          case 178: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        images_ = java.util.Collections.unmodifiableList(images_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Post_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Post_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dk.via.mithus.protobuf.Post.class, dk.via.mithus.protobuf.Post.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STREET_FIELD_NUMBER = 4;
  private volatile java.lang.Object street_;
  /**
   * <code>string street = 4;</code>
   * @return The street.
   */
  @java.lang.Override
  public java.lang.String getStreet() {
    java.lang.Object ref = street_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      street_ = s;
      return s;
    }
  }
  /**
   * <code>string street = 4;</code>
   * @return The bytes for street.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreetBytes() {
    java.lang.Object ref = street_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      street_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AREA_FIELD_NUMBER = 5;
  private double area_;
  /**
   * <code>double area = 5;</code>
   * @return The area.
   */
  @java.lang.Override
  public double getArea() {
    return area_;
  }

  public static final int TYPE_FIELD_NUMBER = 6;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 6;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 6;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAXTENANTS_FIELD_NUMBER = 7;
  private int maxTenants_;
  /**
   * <code>int32 maxTenants = 7;</code>
   * @return The maxTenants.
   */
  @java.lang.Override
  public int getMaxTenants() {
    return maxTenants_;
  }

  public static final int ENERGYRATING_FIELD_NUMBER = 8;
  private volatile java.lang.Object energyRating_;
  /**
   * <code>string energyRating = 8;</code>
   * @return The energyRating.
   */
  @java.lang.Override
  public java.lang.String getEnergyRating() {
    java.lang.Object ref = energyRating_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      energyRating_ = s;
      return s;
    }
  }
  /**
   * <code>string energyRating = 8;</code>
   * @return The bytes for energyRating.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnergyRatingBytes() {
    java.lang.Object ref = energyRating_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      energyRating_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPOSIT_FIELD_NUMBER = 9;
  private double deposit_;
  /**
   * <code>double deposit = 9;</code>
   * @return The deposit.
   */
  @java.lang.Override
  public double getDeposit() {
    return deposit_;
  }

  public static final int MOVEINPRICE_FIELD_NUMBER = 10;
  private double moveInPrice_;
  /**
   * <code>double moveInPrice = 10;</code>
   * @return The moveInPrice.
   */
  @java.lang.Override
  public double getMoveInPrice() {
    return moveInPrice_;
  }

  public static final int UTILITIES_FIELD_NUMBER = 11;
  private double utilities_;
  /**
   * <code>double utilities = 11;</code>
   * @return The utilities.
   */
  @java.lang.Override
  public double getUtilities() {
    return utilities_;
  }

  public static final int MONTHLYRENT_FIELD_NUMBER = 12;
  private double monthlyRent_;
  /**
   * <code>double monthlyRent = 12;</code>
   * @return The monthlyRent.
   */
  @java.lang.Override
  public double getMonthlyRent() {
    return monthlyRent_;
  }

  public static final int STATUS_FIELD_NUMBER = 13;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 13;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 13;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISFURNISHED_FIELD_NUMBER = 14;
  private boolean isFurnished_;
  /**
   * <code>bool isFurnished = 14;</code>
   * @return The isFurnished.
   */
  @java.lang.Override
  public boolean getIsFurnished() {
    return isFurnished_;
  }

  public static final int HASBALCONY_FIELD_NUMBER = 15;
  private boolean hasBalcony_;
  /**
   * <code>bool hasBalcony = 15;</code>
   * @return The hasBalcony.
   */
  @java.lang.Override
  public boolean getHasBalcony() {
    return hasBalcony_;
  }

  public static final int SMOKINGALLOWED_FIELD_NUMBER = 16;
  private boolean smokingAllowed_;
  /**
   * <code>bool smokingAllowed = 16;</code>
   * @return The smokingAllowed.
   */
  @java.lang.Override
  public boolean getSmokingAllowed() {
    return smokingAllowed_;
  }

  public static final int HASPARKING_FIELD_NUMBER = 17;
  private boolean hasParking_;
  /**
   * <code>bool hasParking = 17;</code>
   * @return The hasParking.
   */
  @java.lang.Override
  public boolean getHasParking() {
    return hasParking_;
  }

  public static final int HASDRYER_FIELD_NUMBER = 18;
  private boolean hasDryer_;
  /**
   * <code>bool hasDryer = 18;</code>
   * @return The hasDryer.
   */
  @java.lang.Override
  public boolean getHasDryer() {
    return hasDryer_;
  }

  public static final int HASDISHWASHER_FIELD_NUMBER = 19;
  private boolean hasDishwasher_;
  /**
   * <code>bool hasDishwasher = 19;</code>
   * @return The hasDishwasher.
   */
  @java.lang.Override
  public boolean getHasDishwasher() {
    return hasDishwasher_;
  }

  public static final int HASWASHINGMACHINE_FIELD_NUMBER = 20;
  private boolean hasWashingMachine_;
  /**
   * <code>bool hasWashingMachine = 20;</code>
   * @return The hasWashingMachine.
   */
  @java.lang.Override
  public boolean getHasWashingMachine() {
    return hasWashingMachine_;
  }

  public static final int IMAGES_FIELD_NUMBER = 21;
  private java.util.List<dk.via.mithus.protobuf.Image> images_;
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
   */
  @java.lang.Override
  public java.util.List<dk.via.mithus.protobuf.Image> getImagesList() {
    return images_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dk.via.mithus.protobuf.ImageOrBuilder> 
      getImagesOrBuilderList() {
    return images_;
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
   */
  @java.lang.Override
  public int getImagesCount() {
    return images_.size();
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.Image getImages(int index) {
    return images_.get(index);
  }
  /**
   * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
   */
  @java.lang.Override
  public dk.via.mithus.protobuf.ImageOrBuilder getImagesOrBuilder(
      int index) {
    return images_.get(index);
  }

  public static final int USERID_FIELD_NUMBER = 22;
  private volatile java.lang.Object userId_;
  /**
   * <code>string userId = 22;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string userId = 22;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, street_);
    }
    if (java.lang.Double.doubleToRawLongBits(area_) != 0) {
      output.writeDouble(5, area_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, type_);
    }
    if (maxTenants_ != 0) {
      output.writeInt32(7, maxTenants_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(energyRating_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, energyRating_);
    }
    if (java.lang.Double.doubleToRawLongBits(deposit_) != 0) {
      output.writeDouble(9, deposit_);
    }
    if (java.lang.Double.doubleToRawLongBits(moveInPrice_) != 0) {
      output.writeDouble(10, moveInPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(utilities_) != 0) {
      output.writeDouble(11, utilities_);
    }
    if (java.lang.Double.doubleToRawLongBits(monthlyRent_) != 0) {
      output.writeDouble(12, monthlyRent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, status_);
    }
    if (isFurnished_ != false) {
      output.writeBool(14, isFurnished_);
    }
    if (hasBalcony_ != false) {
      output.writeBool(15, hasBalcony_);
    }
    if (smokingAllowed_ != false) {
      output.writeBool(16, smokingAllowed_);
    }
    if (hasParking_ != false) {
      output.writeBool(17, hasParking_);
    }
    if (hasDryer_ != false) {
      output.writeBool(18, hasDryer_);
    }
    if (hasDishwasher_ != false) {
      output.writeBool(19, hasDishwasher_);
    }
    if (hasWashingMachine_ != false) {
      output.writeBool(20, hasWashingMachine_);
    }
    for (int i = 0; i < images_.size(); i++) {
      output.writeMessage(21, images_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 22, userId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(street_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, street_);
    }
    if (java.lang.Double.doubleToRawLongBits(area_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, area_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, type_);
    }
    if (maxTenants_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, maxTenants_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(energyRating_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, energyRating_);
    }
    if (java.lang.Double.doubleToRawLongBits(deposit_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, deposit_);
    }
    if (java.lang.Double.doubleToRawLongBits(moveInPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, moveInPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(utilities_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, utilities_);
    }
    if (java.lang.Double.doubleToRawLongBits(monthlyRent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, monthlyRent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, status_);
    }
    if (isFurnished_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, isFurnished_);
    }
    if (hasBalcony_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(15, hasBalcony_);
    }
    if (smokingAllowed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(16, smokingAllowed_);
    }
    if (hasParking_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(17, hasParking_);
    }
    if (hasDryer_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(18, hasDryer_);
    }
    if (hasDishwasher_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(19, hasDishwasher_);
    }
    if (hasWashingMachine_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(20, hasWashingMachine_);
    }
    for (int i = 0; i < images_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, images_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, userId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dk.via.mithus.protobuf.Post)) {
      return super.equals(obj);
    }
    dk.via.mithus.protobuf.Post other = (dk.via.mithus.protobuf.Post) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getStreet()
        .equals(other.getStreet())) return false;
    if (java.lang.Double.doubleToLongBits(getArea())
        != java.lang.Double.doubleToLongBits(
            other.getArea())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (getMaxTenants()
        != other.getMaxTenants()) return false;
    if (!getEnergyRating()
        .equals(other.getEnergyRating())) return false;
    if (java.lang.Double.doubleToLongBits(getDeposit())
        != java.lang.Double.doubleToLongBits(
            other.getDeposit())) return false;
    if (java.lang.Double.doubleToLongBits(getMoveInPrice())
        != java.lang.Double.doubleToLongBits(
            other.getMoveInPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getUtilities())
        != java.lang.Double.doubleToLongBits(
            other.getUtilities())) return false;
    if (java.lang.Double.doubleToLongBits(getMonthlyRent())
        != java.lang.Double.doubleToLongBits(
            other.getMonthlyRent())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (getIsFurnished()
        != other.getIsFurnished()) return false;
    if (getHasBalcony()
        != other.getHasBalcony()) return false;
    if (getSmokingAllowed()
        != other.getSmokingAllowed()) return false;
    if (getHasParking()
        != other.getHasParking()) return false;
    if (getHasDryer()
        != other.getHasDryer()) return false;
    if (getHasDishwasher()
        != other.getHasDishwasher()) return false;
    if (getHasWashingMachine()
        != other.getHasWashingMachine()) return false;
    if (!getImagesList()
        .equals(other.getImagesList())) return false;
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + STREET_FIELD_NUMBER;
    hash = (53 * hash) + getStreet().hashCode();
    hash = (37 * hash) + AREA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getArea()));
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + MAXTENANTS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxTenants();
    hash = (37 * hash) + ENERGYRATING_FIELD_NUMBER;
    hash = (53 * hash) + getEnergyRating().hashCode();
    hash = (37 * hash) + DEPOSIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDeposit()));
    hash = (37 * hash) + MOVEINPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMoveInPrice()));
    hash = (37 * hash) + UTILITIES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUtilities()));
    hash = (37 * hash) + MONTHLYRENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMonthlyRent()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + ISFURNISHED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFurnished());
    hash = (37 * hash) + HASBALCONY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasBalcony());
    hash = (37 * hash) + SMOKINGALLOWED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSmokingAllowed());
    hash = (37 * hash) + HASPARKING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasParking());
    hash = (37 * hash) + HASDRYER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasDryer());
    hash = (37 * hash) + HASDISHWASHER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasDishwasher());
    hash = (37 * hash) + HASWASHINGMACHINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasWashingMachine());
    if (getImagesCount() > 0) {
      hash = (37 * hash) + IMAGES_FIELD_NUMBER;
      hash = (53 * hash) + getImagesList().hashCode();
    }
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dk.via.mithus.protobuf.Post parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Post parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.Post parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dk.via.mithus.protobuf.Post parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dk.via.mithus.protobuf.Post prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dk.via.mithus.protobuf.Post}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dk.via.mithus.protobuf.Post)
      dk.via.mithus.protobuf.PostOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Post_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Post_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dk.via.mithus.protobuf.Post.class, dk.via.mithus.protobuf.Post.Builder.class);
    }

    // Construct using dk.via.mithus.protobuf.Post.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      title_ = "";

      description_ = "";

      street_ = "";

      area_ = 0D;

      type_ = "";

      maxTenants_ = 0;

      energyRating_ = "";

      deposit_ = 0D;

      moveInPrice_ = 0D;

      utilities_ = 0D;

      monthlyRent_ = 0D;

      status_ = "";

      isFurnished_ = false;

      hasBalcony_ = false;

      smokingAllowed_ = false;

      hasParking_ = false;

      hasDryer_ = false;

      hasDishwasher_ = false;

      hasWashingMachine_ = false;

      if (imagesBuilder_ == null) {
        images_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        imagesBuilder_.clear();
      }
      userId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dk.via.mithus.protobuf.Protobuf.internal_static_dk_via_mithus_protobuf_Post_descriptor;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.Post getDefaultInstanceForType() {
      return dk.via.mithus.protobuf.Post.getDefaultInstance();
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.Post build() {
      dk.via.mithus.protobuf.Post result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dk.via.mithus.protobuf.Post buildPartial() {
      dk.via.mithus.protobuf.Post result = new dk.via.mithus.protobuf.Post(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.title_ = title_;
      result.description_ = description_;
      result.street_ = street_;
      result.area_ = area_;
      result.type_ = type_;
      result.maxTenants_ = maxTenants_;
      result.energyRating_ = energyRating_;
      result.deposit_ = deposit_;
      result.moveInPrice_ = moveInPrice_;
      result.utilities_ = utilities_;
      result.monthlyRent_ = monthlyRent_;
      result.status_ = status_;
      result.isFurnished_ = isFurnished_;
      result.hasBalcony_ = hasBalcony_;
      result.smokingAllowed_ = smokingAllowed_;
      result.hasParking_ = hasParking_;
      result.hasDryer_ = hasDryer_;
      result.hasDishwasher_ = hasDishwasher_;
      result.hasWashingMachine_ = hasWashingMachine_;
      if (imagesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          images_ = java.util.Collections.unmodifiableList(images_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.images_ = images_;
      } else {
        result.images_ = imagesBuilder_.build();
      }
      result.userId_ = userId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dk.via.mithus.protobuf.Post) {
        return mergeFrom((dk.via.mithus.protobuf.Post)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dk.via.mithus.protobuf.Post other) {
      if (other == dk.via.mithus.protobuf.Post.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getStreet().isEmpty()) {
        street_ = other.street_;
        onChanged();
      }
      if (other.getArea() != 0D) {
        setArea(other.getArea());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.getMaxTenants() != 0) {
        setMaxTenants(other.getMaxTenants());
      }
      if (!other.getEnergyRating().isEmpty()) {
        energyRating_ = other.energyRating_;
        onChanged();
      }
      if (other.getDeposit() != 0D) {
        setDeposit(other.getDeposit());
      }
      if (other.getMoveInPrice() != 0D) {
        setMoveInPrice(other.getMoveInPrice());
      }
      if (other.getUtilities() != 0D) {
        setUtilities(other.getUtilities());
      }
      if (other.getMonthlyRent() != 0D) {
        setMonthlyRent(other.getMonthlyRent());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getIsFurnished() != false) {
        setIsFurnished(other.getIsFurnished());
      }
      if (other.getHasBalcony() != false) {
        setHasBalcony(other.getHasBalcony());
      }
      if (other.getSmokingAllowed() != false) {
        setSmokingAllowed(other.getSmokingAllowed());
      }
      if (other.getHasParking() != false) {
        setHasParking(other.getHasParking());
      }
      if (other.getHasDryer() != false) {
        setHasDryer(other.getHasDryer());
      }
      if (other.getHasDishwasher() != false) {
        setHasDishwasher(other.getHasDishwasher());
      }
      if (other.getHasWashingMachine() != false) {
        setHasWashingMachine(other.getHasWashingMachine());
      }
      if (imagesBuilder_ == null) {
        if (!other.images_.isEmpty()) {
          if (images_.isEmpty()) {
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImagesIsMutable();
            images_.addAll(other.images_);
          }
          onChanged();
        }
      } else {
        if (!other.images_.isEmpty()) {
          if (imagesBuilder_.isEmpty()) {
            imagesBuilder_.dispose();
            imagesBuilder_ = null;
            images_ = other.images_;
            bitField0_ = (bitField0_ & ~0x00000001);
            imagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getImagesFieldBuilder() : null;
          } else {
            imagesBuilder_.addAllMessages(other.images_);
          }
        }
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dk.via.mithus.protobuf.Post parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dk.via.mithus.protobuf.Post) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object street_ = "";
    /**
     * <code>string street = 4;</code>
     * @return The street.
     */
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string street = 4;</code>
     * @return The bytes for street.
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string street = 4;</code>
     * @param value The street to set.
     * @return This builder for chaining.
     */
    public Builder setStreet(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      street_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string street = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreet() {
      
      street_ = getDefaultInstance().getStreet();
      onChanged();
      return this;
    }
    /**
     * <code>string street = 4;</code>
     * @param value The bytes for street to set.
     * @return This builder for chaining.
     */
    public Builder setStreetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      street_ = value;
      onChanged();
      return this;
    }

    private double area_ ;
    /**
     * <code>double area = 5;</code>
     * @return The area.
     */
    @java.lang.Override
    public double getArea() {
      return area_;
    }
    /**
     * <code>double area = 5;</code>
     * @param value The area to set.
     * @return This builder for chaining.
     */
    public Builder setArea(double value) {
      
      area_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double area = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearArea() {
      
      area_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 6;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 6;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 6;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 6;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private int maxTenants_ ;
    /**
     * <code>int32 maxTenants = 7;</code>
     * @return The maxTenants.
     */
    @java.lang.Override
    public int getMaxTenants() {
      return maxTenants_;
    }
    /**
     * <code>int32 maxTenants = 7;</code>
     * @param value The maxTenants to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTenants(int value) {
      
      maxTenants_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxTenants = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTenants() {
      
      maxTenants_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object energyRating_ = "";
    /**
     * <code>string energyRating = 8;</code>
     * @return The energyRating.
     */
    public java.lang.String getEnergyRating() {
      java.lang.Object ref = energyRating_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        energyRating_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string energyRating = 8;</code>
     * @return The bytes for energyRating.
     */
    public com.google.protobuf.ByteString
        getEnergyRatingBytes() {
      java.lang.Object ref = energyRating_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        energyRating_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string energyRating = 8;</code>
     * @param value The energyRating to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyRating(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      energyRating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string energyRating = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnergyRating() {
      
      energyRating_ = getDefaultInstance().getEnergyRating();
      onChanged();
      return this;
    }
    /**
     * <code>string energyRating = 8;</code>
     * @param value The bytes for energyRating to set.
     * @return This builder for chaining.
     */
    public Builder setEnergyRatingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      energyRating_ = value;
      onChanged();
      return this;
    }

    private double deposit_ ;
    /**
     * <code>double deposit = 9;</code>
     * @return The deposit.
     */
    @java.lang.Override
    public double getDeposit() {
      return deposit_;
    }
    /**
     * <code>double deposit = 9;</code>
     * @param value The deposit to set.
     * @return This builder for chaining.
     */
    public Builder setDeposit(double value) {
      
      deposit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double deposit = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeposit() {
      
      deposit_ = 0D;
      onChanged();
      return this;
    }

    private double moveInPrice_ ;
    /**
     * <code>double moveInPrice = 10;</code>
     * @return The moveInPrice.
     */
    @java.lang.Override
    public double getMoveInPrice() {
      return moveInPrice_;
    }
    /**
     * <code>double moveInPrice = 10;</code>
     * @param value The moveInPrice to set.
     * @return This builder for chaining.
     */
    public Builder setMoveInPrice(double value) {
      
      moveInPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double moveInPrice = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoveInPrice() {
      
      moveInPrice_ = 0D;
      onChanged();
      return this;
    }

    private double utilities_ ;
    /**
     * <code>double utilities = 11;</code>
     * @return The utilities.
     */
    @java.lang.Override
    public double getUtilities() {
      return utilities_;
    }
    /**
     * <code>double utilities = 11;</code>
     * @param value The utilities to set.
     * @return This builder for chaining.
     */
    public Builder setUtilities(double value) {
      
      utilities_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double utilities = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearUtilities() {
      
      utilities_ = 0D;
      onChanged();
      return this;
    }

    private double monthlyRent_ ;
    /**
     * <code>double monthlyRent = 12;</code>
     * @return The monthlyRent.
     */
    @java.lang.Override
    public double getMonthlyRent() {
      return monthlyRent_;
    }
    /**
     * <code>double monthlyRent = 12;</code>
     * @param value The monthlyRent to set.
     * @return This builder for chaining.
     */
    public Builder setMonthlyRent(double value) {
      
      monthlyRent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double monthlyRent = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearMonthlyRent() {
      
      monthlyRent_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 13;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 13;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 13;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 13;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private boolean isFurnished_ ;
    /**
     * <code>bool isFurnished = 14;</code>
     * @return The isFurnished.
     */
    @java.lang.Override
    public boolean getIsFurnished() {
      return isFurnished_;
    }
    /**
     * <code>bool isFurnished = 14;</code>
     * @param value The isFurnished to set.
     * @return This builder for chaining.
     */
    public Builder setIsFurnished(boolean value) {
      
      isFurnished_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isFurnished = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFurnished() {
      
      isFurnished_ = false;
      onChanged();
      return this;
    }

    private boolean hasBalcony_ ;
    /**
     * <code>bool hasBalcony = 15;</code>
     * @return The hasBalcony.
     */
    @java.lang.Override
    public boolean getHasBalcony() {
      return hasBalcony_;
    }
    /**
     * <code>bool hasBalcony = 15;</code>
     * @param value The hasBalcony to set.
     * @return This builder for chaining.
     */
    public Builder setHasBalcony(boolean value) {
      
      hasBalcony_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasBalcony = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasBalcony() {
      
      hasBalcony_ = false;
      onChanged();
      return this;
    }

    private boolean smokingAllowed_ ;
    /**
     * <code>bool smokingAllowed = 16;</code>
     * @return The smokingAllowed.
     */
    @java.lang.Override
    public boolean getSmokingAllowed() {
      return smokingAllowed_;
    }
    /**
     * <code>bool smokingAllowed = 16;</code>
     * @param value The smokingAllowed to set.
     * @return This builder for chaining.
     */
    public Builder setSmokingAllowed(boolean value) {
      
      smokingAllowed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool smokingAllowed = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearSmokingAllowed() {
      
      smokingAllowed_ = false;
      onChanged();
      return this;
    }

    private boolean hasParking_ ;
    /**
     * <code>bool hasParking = 17;</code>
     * @return The hasParking.
     */
    @java.lang.Override
    public boolean getHasParking() {
      return hasParking_;
    }
    /**
     * <code>bool hasParking = 17;</code>
     * @param value The hasParking to set.
     * @return This builder for chaining.
     */
    public Builder setHasParking(boolean value) {
      
      hasParking_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasParking = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasParking() {
      
      hasParking_ = false;
      onChanged();
      return this;
    }

    private boolean hasDryer_ ;
    /**
     * <code>bool hasDryer = 18;</code>
     * @return The hasDryer.
     */
    @java.lang.Override
    public boolean getHasDryer() {
      return hasDryer_;
    }
    /**
     * <code>bool hasDryer = 18;</code>
     * @param value The hasDryer to set.
     * @return This builder for chaining.
     */
    public Builder setHasDryer(boolean value) {
      
      hasDryer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasDryer = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasDryer() {
      
      hasDryer_ = false;
      onChanged();
      return this;
    }

    private boolean hasDishwasher_ ;
    /**
     * <code>bool hasDishwasher = 19;</code>
     * @return The hasDishwasher.
     */
    @java.lang.Override
    public boolean getHasDishwasher() {
      return hasDishwasher_;
    }
    /**
     * <code>bool hasDishwasher = 19;</code>
     * @param value The hasDishwasher to set.
     * @return This builder for chaining.
     */
    public Builder setHasDishwasher(boolean value) {
      
      hasDishwasher_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasDishwasher = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasDishwasher() {
      
      hasDishwasher_ = false;
      onChanged();
      return this;
    }

    private boolean hasWashingMachine_ ;
    /**
     * <code>bool hasWashingMachine = 20;</code>
     * @return The hasWashingMachine.
     */
    @java.lang.Override
    public boolean getHasWashingMachine() {
      return hasWashingMachine_;
    }
    /**
     * <code>bool hasWashingMachine = 20;</code>
     * @param value The hasWashingMachine to set.
     * @return This builder for chaining.
     */
    public Builder setHasWashingMachine(boolean value) {
      
      hasWashingMachine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasWashingMachine = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasWashingMachine() {
      
      hasWashingMachine_ = false;
      onChanged();
      return this;
    }

    private java.util.List<dk.via.mithus.protobuf.Image> images_ =
      java.util.Collections.emptyList();
    private void ensureImagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        images_ = new java.util.ArrayList<dk.via.mithus.protobuf.Image>(images_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder> imagesBuilder_;

    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Image> getImagesList() {
      if (imagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(images_);
      } else {
        return imagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public int getImagesCount() {
      if (imagesBuilder_ == null) {
        return images_.size();
      } else {
        return imagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public dk.via.mithus.protobuf.Image getImages(int index) {
      if (imagesBuilder_ == null) {
        return images_.get(index);
      } else {
        return imagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder setImages(
        int index, dk.via.mithus.protobuf.Image value) {
      if (imagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images_.set(index, value);
        onChanged();
      } else {
        imagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder setImages(
        int index, dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        images_.set(index, builderForValue.build());
        onChanged();
      } else {
        imagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder addImages(dk.via.mithus.protobuf.Image value) {
      if (imagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images_.add(value);
        onChanged();
      } else {
        imagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder addImages(
        int index, dk.via.mithus.protobuf.Image value) {
      if (imagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images_.add(index, value);
        onChanged();
      } else {
        imagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder addImages(
        dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        images_.add(builderForValue.build());
        onChanged();
      } else {
        imagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder addImages(
        int index, dk.via.mithus.protobuf.Image.Builder builderForValue) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        images_.add(index, builderForValue.build());
        onChanged();
      } else {
        imagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder addAllImages(
        java.lang.Iterable<? extends dk.via.mithus.protobuf.Image> values) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, images_);
        onChanged();
      } else {
        imagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder clearImages() {
      if (imagesBuilder_ == null) {
        images_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        imagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public Builder removeImages(int index) {
      if (imagesBuilder_ == null) {
        ensureImagesIsMutable();
        images_.remove(index);
        onChanged();
      } else {
        imagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder getImagesBuilder(
        int index) {
      return getImagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public dk.via.mithus.protobuf.ImageOrBuilder getImagesOrBuilder(
        int index) {
      if (imagesBuilder_ == null) {
        return images_.get(index);  } else {
        return imagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public java.util.List<? extends dk.via.mithus.protobuf.ImageOrBuilder> 
         getImagesOrBuilderList() {
      if (imagesBuilder_ != null) {
        return imagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(images_);
      }
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder addImagesBuilder() {
      return getImagesFieldBuilder().addBuilder(
          dk.via.mithus.protobuf.Image.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public dk.via.mithus.protobuf.Image.Builder addImagesBuilder(
        int index) {
      return getImagesFieldBuilder().addBuilder(
          index, dk.via.mithus.protobuf.Image.getDefaultInstance());
    }
    /**
     * <code>repeated .dk.via.mithus.protobuf.Image images = 21;</code>
     */
    public java.util.List<dk.via.mithus.protobuf.Image.Builder> 
         getImagesBuilderList() {
      return getImagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder> 
        getImagesFieldBuilder() {
      if (imagesBuilder_ == null) {
        imagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            dk.via.mithus.protobuf.Image, dk.via.mithus.protobuf.Image.Builder, dk.via.mithus.protobuf.ImageOrBuilder>(
                images_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        images_ = null;
      }
      return imagesBuilder_;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>string userId = 22;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userId = 22;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userId = 22;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 22;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dk.via.mithus.protobuf.Post)
  }

  // @@protoc_insertion_point(class_scope:dk.via.mithus.protobuf.Post)
  private static final dk.via.mithus.protobuf.Post DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dk.via.mithus.protobuf.Post();
  }

  public static dk.via.mithus.protobuf.Post getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Post>
      PARSER = new com.google.protobuf.AbstractParser<Post>() {
    @java.lang.Override
    public Post parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Post(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Post> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Post> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dk.via.mithus.protobuf.Post getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

