// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface PostStatusesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.PostStatuses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dk.via.mithus.protobuf.PostStatus available = 1;</code>
   * @return Whether the available field is set.
   */
  boolean hasAvailable();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus available = 1;</code>
   * @return The available.
   */
  dk.via.mithus.protobuf.PostStatus getAvailable();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus available = 1;</code>
   */
  dk.via.mithus.protobuf.PostStatusOrBuilder getAvailableOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.PostStatus reserved = 2;</code>
   * @return Whether the reserved field is set.
   */
  boolean hasReserved();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus reserved = 2;</code>
   * @return The reserved.
   */
  dk.via.mithus.protobuf.PostStatus getReserved();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus reserved = 2;</code>
   */
  dk.via.mithus.protobuf.PostStatusOrBuilder getReservedOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.PostStatus hidden = 3;</code>
   * @return Whether the hidden field is set.
   */
  boolean hasHidden();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus hidden = 3;</code>
   * @return The hidden.
   */
  dk.via.mithus.protobuf.PostStatus getHidden();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus hidden = 3;</code>
   */
  dk.via.mithus.protobuf.PostStatusOrBuilder getHiddenOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.PostStatus denied = 4;</code>
   * @return Whether the denied field is set.
   */
  boolean hasDenied();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus denied = 4;</code>
   * @return The denied.
   */
  dk.via.mithus.protobuf.PostStatus getDenied();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus denied = 4;</code>
   */
  dk.via.mithus.protobuf.PostStatusOrBuilder getDeniedOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.PostStatus pending = 5;</code>
   * @return Whether the pending field is set.
   */
  boolean hasPending();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus pending = 5;</code>
   * @return The pending.
   */
  dk.via.mithus.protobuf.PostStatus getPending();
  /**
   * <code>.dk.via.mithus.protobuf.PostStatus pending = 5;</code>
   */
  dk.via.mithus.protobuf.PostStatusOrBuilder getPendingOrBuilder();
}
