// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface RoleUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.RoleUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 roleId = 2;</code>
   * @return The roleId.
   */
  long getRoleId();
}
