// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface RolesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.Roles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dk.via.mithus.protobuf.Role roles = 1;</code>
   */
  java.util.List<dk.via.mithus.protobuf.Role> 
      getRolesList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.Role roles = 1;</code>
   */
  dk.via.mithus.protobuf.Role getRoles(int index);
  /**
   * <code>repeated .dk.via.mithus.protobuf.Role roles = 1;</code>
   */
  int getRolesCount();
  /**
   * <code>repeated .dk.via.mithus.protobuf.Role roles = 1;</code>
   */
  java.util.List<? extends dk.via.mithus.protobuf.RoleOrBuilder> 
      getRolesOrBuilderList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.Role roles = 1;</code>
   */
  dk.via.mithus.protobuf.RoleOrBuilder getRolesOrBuilder(
      int index);
}
