// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface RolesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.Roles)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dk.via.mithus.protobuf.Role client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.dk.via.mithus.protobuf.Role client = 1;</code>
   * @return The client.
   */
  dk.via.mithus.protobuf.Role getClient();
  /**
   * <code>.dk.via.mithus.protobuf.Role client = 1;</code>
   */
  dk.via.mithus.protobuf.RoleOrBuilder getClientOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.Role landlord = 2;</code>
   * @return Whether the landlord field is set.
   */
  boolean hasLandlord();
  /**
   * <code>.dk.via.mithus.protobuf.Role landlord = 2;</code>
   * @return The landlord.
   */
  dk.via.mithus.protobuf.Role getLandlord();
  /**
   * <code>.dk.via.mithus.protobuf.Role landlord = 2;</code>
   */
  dk.via.mithus.protobuf.RoleOrBuilder getLandlordOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.Role moderator = 3;</code>
   * @return Whether the moderator field is set.
   */
  boolean hasModerator();
  /**
   * <code>.dk.via.mithus.protobuf.Role moderator = 3;</code>
   * @return The moderator.
   */
  dk.via.mithus.protobuf.Role getModerator();
  /**
   * <code>.dk.via.mithus.protobuf.Role moderator = 3;</code>
   */
  dk.via.mithus.protobuf.RoleOrBuilder getModeratorOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.Role administrator = 4;</code>
   * @return Whether the administrator field is set.
   */
  boolean hasAdministrator();
  /**
   * <code>.dk.via.mithus.protobuf.Role administrator = 4;</code>
   * @return The administrator.
   */
  dk.via.mithus.protobuf.Role getAdministrator();
  /**
   * <code>.dk.via.mithus.protobuf.Role administrator = 4;</code>
   */
  dk.via.mithus.protobuf.RoleOrBuilder getAdministratorOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.Role inactive = 5;</code>
   * @return Whether the inactive field is set.
   */
  boolean hasInactive();
  /**
   * <code>.dk.via.mithus.protobuf.Role inactive = 5;</code>
   * @return The inactive.
   */
  dk.via.mithus.protobuf.Role getInactive();
  /**
   * <code>.dk.via.mithus.protobuf.Role inactive = 5;</code>
   */
  dk.via.mithus.protobuf.RoleOrBuilder getInactiveOrBuilder();

  /**
   * <code>.dk.via.mithus.protobuf.Role pending = 6;</code>
   * @return Whether the pending field is set.
   */
  boolean hasPending();
  /**
   * <code>.dk.via.mithus.protobuf.Role pending = 6;</code>
   * @return The pending.
   */
  dk.via.mithus.protobuf.Role getPending();
  /**
   * <code>.dk.via.mithus.protobuf.Role pending = 6;</code>
   */
  dk.via.mithus.protobuf.RoleOrBuilder getPendingOrBuilder();
}
