// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface UsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.Users)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .dk.via.mithus.protobuf.User users = 1;</code>
   */
  java.util.List<dk.via.mithus.protobuf.User> 
      getUsersList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.User users = 1;</code>
   */
  dk.via.mithus.protobuf.User getUsers(int index);
  /**
   * <code>repeated .dk.via.mithus.protobuf.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .dk.via.mithus.protobuf.User users = 1;</code>
   */
  java.util.List<? extends dk.via.mithus.protobuf.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .dk.via.mithus.protobuf.User users = 1;</code>
   */
  dk.via.mithus.protobuf.UserOrBuilder getUsersOrBuilder(
      int index);
}
