// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package dk.via.mithus.protobuf;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dk.via.mithus.protobuf.Void)
    com.google.protobuf.MessageOrBuilder {
}
